### ISSUE TITLE
“Launch from Steam first”

### ISSUE THREAD

**Issue by JohnTotonchi** [Seblor/Soundpaddon#1]
I own the full version, I am not using the trial, to clarify.

The first time I tried to use it I had Soundpad open already and then I launched Soundpaddon. That didn’t work, it said to launch it with Steam first. 
so then I closed soundpad and then it gave me four or five errors (from soundpaddon) that I had to launch it from Steam first even after I just closed sound pad. When I tried to reopen it and the errors were still going, it just closed sound pad automatically. I don’t know what to do.

Please ask me If i need to clarify anything because I wrote this while taking a shit.

**Comment by JohnTotonchi** [comment]
1- What is your operating system display language ? 
I am using English, US
2- When Soundpad is opened and you open Soundpaddon, you get an error. If you ignore the error, does it stop Soundpaddon from working or is it fine afterwards ?
There is no error if i already had soundpad open prior to opening Soundpaddon. I say "no error" but I mean there is no error "popup", soundpaddon still does not detect soundpad, nor does the mobile control display anything.
3- What version of Soundpad are you using ?
I am using version 4.03, the latest version.
4- Can you tell me what is the output of the command REG QUERY HKEY_CLASSES_ROOT\Soundpad\shell\open\command ?

In PowerShell, the output is: `    (Default)    REG_SZ    "B:\SteamLibrary\steamapps\common\Soundpad\Soundpad.exe" -c "%1"`

Not sure if this means anything, but if i open the exe at that location, it gives me the same "open from steam" notice, and does not launch. 
Sorry for the late reply. Let me know if I can tell you anything else!

**Comment by Seblor** [comment]
> Not sure if this means anything, but if i open the exe at that location, it gives me the same "open from steam" notice, and does not launch.

Yes that's the same issue since Soundpaddon attempts to open the executable. I'm working on a solution to that but it seems to be a new behavior.

For the mobile preview that appears blank, I have more questions x)

1- Is it plain white or is there a colored background ?
2- if you open the console with ctrl + shift + I, can you screenshot the errors (if there are any) ?
3- What can you see if you go to `https://127-0-0-1.local-ip.sh:8555/panel/mobile` in your browser ? (preferably a chromium-based browser)

**Comment by JohnTotonchi** [comment]
![IMG_8816](https://github.com/Seblor/Soundpaddon/assets/116926560/44311101-0333-46cc-91f6-ae98a3eb32af)
 
I am busy, i can give you this right now

**Comment by JohnTotonchi** [comment]
i was answering the first question, this is what i see when i try to pair with my phone,,, nothing shows up

**Comment by Seblor** [comment]
Oh my bad I thought you meant the mobile preview on the desktop app.

Can you tell me if the preview is working fine on the dekstop app ?

**Comment by JohnTotonchi** [comment]
1- Is it plain white or is there a colored background ?

yk

2- if you open the console with ctrl + shift + I, can you screenshot the errors (if there are any) ?

![image](https://github.com/Seblor/Soundpaddon/assets/116926560/ce717f0b-9710-4ccc-a21f-2968bdef00ce)

3- What can you see if you go to https://127-0-0-1.local-ip.sh:8555/panel/mobile in your browser ? (preferably a chromium-based browser)

In desktop mode: ------------------------------------------

![image](https://github.com/Seblor/Soundpaddon/assets/116926560/4d5aa46e-18a1-4a28-b0ea-669279d8df6e)

In Firefox Responsive design mode (obviously not Chromium): ---------------------------------------

![image](https://github.com/Seblor/Soundpaddon/assets/116926560/1376dd6d-b9ff-45d5-81b5-1aea68c3cb6c)

**Comment by JohnTotonchi** [comment]
Would you be fine with discord? Or keep it here for the sake of others with the same problem...

**Comment by JohnTotonchi** [comment]
Also, clarifying, I bought SoundPad AGAIN, NOT from steam. Since then, soundpaddon can OPEN soundpad fine, just no functionality.

**Comment by JohnTotonchi** [comment]
Errors after a fresh soundpaddon boot (and success with opening SoundPad):
![image](https://github.com/Seblor/Soundpaddon/assets/116926560/44ae00a1-c5ea-4224-9ac7-48169cd9a6e1)

**Comment by JohnTotonchi** [comment]
[127-0-0-1.local-ip.sh-1718310104085.log](https://github.com/user-attachments/files/15828326/127-0-0-1.local-ip.sh-1718310104085.log)

**Comment by Seblor** [comment]
We can go on Discord yeah, I have a support server : https://support.soundpaddon.app/

**Comment by Seblor** [comment]
All issues have been resolved in v1.1.0 :)
